name: Deploy
on:
  push:
    branches:
      - main
    tags:
      - "!*"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: scratchfoundation/scratch-gui
          ref: develop
          path: ./scratch-gui
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
        working-directory: ./scratch-gui
      - run: npm run build
        working-directory: ./scratch-gui
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./scratch-gui/build
