name: Deploy
on:
  push:
    branches:
      - main
    tags:
      - "!*"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout scratch-gui
        uses: actions/checkout@v4
        with:
          repository: scratchfoundation/scratch-gui
          ref: develop
          path: ./scratch-gui
      - name: Setup Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
        working-directory: ./scratch-gui
      - name: Modify Scratch
        uses: bricklife/scratch-modifier@main
        with:
          scratch-gui-dir: ./scratch-gui
          logo-file: ./demo/logo.svg
          home-url: 'https://bricklife.com/scratch-modifier/'
      - run: npm run build
        working-directory: ./scratch-gui
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./scratch-gui/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
